[package]
name = "rgbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread", "time", "process", "sync", "io-util", "net"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.2"
tracing = "0.1.38"
gtk-layer-shell = "0.6.0"
lazy_static = "1.4.0"
hyprland = "0.3.4"
lxinfo = "0.1.2"
stray = "0.1.3"
glib = "0.17.2"
gdk-pixbuf = "0.17.0"
json = "0.12.4"
gtk = "0.17.0"
gdk = "0.17.0"
regex = "1"
chrono = "0.4"
pipewire = "0.6.0"
async-std = "1.12.0"
serde_json = "1.0.96"