[package]
name = "rgbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing-tree = "0.2.2"
tracing = "0.1.37"

regex = "1"
chrono = "0.4"
serde_json = "1.0.96"

gtk-layer-shell = "0.6.1"
glib = "0.17.10"
gdk-pixbuf = "0.17.10"
gtk = "0.17.1"
gdk = "0.17.1"
gio = "0.17.10"
